### ISSUE TITLE
Write "About" text

### ISSUE THREAD

**Issue by martinheidegger** [school-lunch2050/kyushoku2050.org#1]
The About pages have been added to to the site, but they are missing content:

https://github.com/school-lunch2050/kyushoku2050.org/blob/main/content/about_en.md
https://github.com/school-lunch2050/kyushoku2050.org/blob/main/content/about_ja.md
https://github.com/school-lunch2050/kyushoku2050.org/blob/main/content/about_ja-simple.md

**Comment by martinheidegger** [comment]
Thank you for adding the about text, let me add a few improvements about the license before translating it to japanese.

Note: you can also specify links by setting`[<text>](<url>)` to the Sustena homepage or feast.

**Comment by martinheidegger** [comment]
@Yu-Mat from my side the about text is finished, it may be good to also update the japanese version.

**Comment by Yu-Mat** [comment]
Done! at this point, I just connected the license information in the rubied about page with the about page (without rubies).
