### ISSUE TITLE
Text missing: Desperate home_sprouts

### ISSUE THREAD

**Issue by martinheidegger** [school-lunch2050/kyushoku2050.org#12]
The japanese and english texts for "home_sprouts" on the desperate illustration are missing:

https://github.com/school-lunch2050/kyushoku2050.org/blob/9aa5c6b906c5655e4dc2e5e6370236d9e8dbb499/lang/messages.ja.yaml#L197
https://github.com/school-lunch2050/kyushoku2050.org/blob/9aa5c6b906c5655e4dc2e5e6370236d9e8dbb499/lang/messages.ja-simple.yaml#L139

**Comment by spiegelmix** [comment]
strange it was missing, but here is the adult version: 
各家庭でさまざまなスプラウトを育て、インスタント食品に足りない、栄養素、いろどり、味をそえています。
and the kids version:
おうちで色々なスプラウトを育て、インスタント食品に足りない、栄養素、いろどり、味をそえています。
I also realized I did not take a separate picture of the sprouts now one with the sprouts and the milk together.

**Comment by spiegelmix** [comment]
I added the sprouts to the menu item text and had to adjust also the scenario descriptive:
en: In class grown sprouts from various seeds add color, micro-nutrients and taste to the common ready meals with long shelf-life. 
jp: 各クラスでさまざまなスプラウトを育て、インスタント食品に足りない、栄養素、いろどり、味をそえています。
e-jp: クラスで色々なスプラウトを育て、インスタント食品に足りない、栄養素、いろどり、味をそえています。

menu: Broccoli sprouts ブロコリスプラウト

descriptor: 
Milk replacement with all the necessary nutrients regionally produced in Kansai and fresh sprouts
必要な栄養素と新鮮なスプラウトがすべてはいった飲み物

**Comment by martinheidegger** [comment]
Closed with:

- https://github.com/school-lunch2050/kyushoku2050.org/commit/c525dd4baf0dfcd0696ceedd12559b64cef3787e#diff-4ff253fc0c4b3c6f594a4bfa25acf23c1d737fabf57858949b259d01438b1288R278
- https://github.com/school-lunch2050/kyushoku2050.org/commit/c525dd4baf0dfcd0696ceedd12559b64cef3787e#diff-d8675d5a7b9e79446495b598302fda0877c1510e440fc8774a2404a0dd801b9aR168
- 8beb8ce6c91d6867dce770ea1acabf87273c074c
