### ISSUE TITLE
text-image frames over scenarios

### ISSUE THREAD

**Issue by spiegelmix** [school-lunch2050/kyushoku2050.org#16]
the seed banks frame should extend further to the left including the schedule board if possible
![image](https://user-images.githubusercontent.com/75411479/109139116-7c5deb00-779e-11eb-9987-cbd2ff300da1.png)

**Comment by martinheidegger** [comment]
Fixed in https://github.com/school-lunch2050/kyushoku2050.org/commit/8e862de814fb0e1393f2519e4af6d082e4248bcc
