### ISSUE TITLE
Add old browser warning

### ISSUE THREAD

**Issue by martinheidegger** [school-lunch2050/kyushoku2050.org#25]
Add test and display to warn that the browser used is too old for this site.
Specifically known to not work: Internet Explorer and older Metro browsers.

**Comment by martinheidegger** [comment]
Warning added in 46f7d66a1ef0721efa1bfea2051e66706e1f159f, 5baee9ee9fddfa841273b577ff2141cb87193b0c, 4fec6b9a702c64aacd0c7e63d3fe8ac27df964a9

<img width="1009" alt="Screen Shot 2021-03-05 at 21 52 53" src="https://user-images.githubusercontent.com/914122/110120487-74d2bd80-7e00-11eb-9fd6-865c394c227d.png">

@Yu-Mat Could you maybe take a look at the phrasing? The text can be found here: https://github.com/school-lunch2050/kyushoku2050.org/blob/46f7d66a1ef0721efa1bfea2051e66706e1f159f/nuxt.config.js#L63-L64

**Comment by Yu-Mat** [comment]
Let me post now before I forget:
True to the original: 
```
'<p lang="ja">このサイトはご利用中のブラウザに対応していません。最新版のブラウザをダウンロードしてご利用ください。</p>'
```
To make sure "the site doesn't support Internet Explorer": 
```
'<p lang="ja">このサイトはご利用中のブラウザに対応していません。Internet Explorerを除く最新版のブラウザをダウンロードしてご利用ください。</p>'
```

**Comment by martinheidegger** [comment]
Closed in https://github.com/school-lunch2050/kyushoku2050.org/commit/169447ec90b7c12b05bc6e269d18412cdb9cad71
