### ISSUE TITLE
scenario artwork is covered 

### ISSUE THREAD

**Issue by spiegelmix** [school-lunch2050/kyushoku2050.org#37]
Seems now the top part of the art work is covered, but only after I uncovered all of them. only the garden scenario.

![image](https://user-images.githubusercontent.com/75411479/125270856-ac1c2280-e33c-11eb-8ee7-e086dd6a65d1.png)

**Comment by martinheidegger** [comment]
@spiegelmix I am not able to reproduce it, in my browser it looks fine. What browser/screen resolution do you use? Can you maybe record a screen-video? (Maybe [gyazo](https://gyazo.com/download) works for you?)

**Comment by spiegelmix** [comment]
Now it also works normally again here. Let's close it then. thanks for the quick reply!

**Comment by martinheidegger** [comment]
This sort of issues tend to come back :wink: Next time it would be good to take a video and look a little bit around to see what was done different. (and if a refresh fixes the issue)
