### ISSUE TITLE
Add plausible request tracking

### ISSUE THREAD

**Issue by martinheidegger** [school-lunch2050/kyushoku2050.org#8]
The [plausible](https://stats.kyushoku2050.org/js/index.js) domain setup is ready. Now its possible to add tracking of visitors.

**Comment by martinheidegger** [comment]
Implemented in f526d517b6ade85a1c8ce8a8316fc62fe2384aad - @spiegelmix can you check if requests get tracked in the user interface?

**Comment by spiegelmix** [comment]
That's how it looks like 
![Screenshot 2021-02-25 093308](https://user-images.githubusercontent.com/75411479/109085172-81924a00-774c-11eb-8343-d1883ff4eaa4.jpg)

**Comment by martinheidegger** [comment]
Seems like it works!
